---
- hosts: master
  vars_files:
    - defaults/main.yaml
  become: yes
  become_method: sudo
  roles:
    - kube-master

- hosts: worker
  vars_files:
    - defaults/main.yaml
  become: yes
  become_method: sudo
  roles:
    - kube-worker
